### PR TITLE
Update to version 0.6.0

### PR DESCRIPTION
**Pull request by holgern**
I need dateparser 0.6.0. Please merge.

Thank you!

### CODE REVIEW

**Comment by ocefpaf** [comment]
@holgern are you committing the CI config changes by hand? We have a bot for that to ensure we don't make mistakes.

@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by holgern** [comment]
Thank you, I didn't know this.

**Comment by ocefpaf** [comment]
It is relatively new. Here is the list of what you can do with it: https://conda-forge.org/docs/webservice.html

**Pull request merged**
